env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: "module"
extends:
  - prettier
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      ignoreRestSiblings: true
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: false
      allowTypedFunctionExpressions: true
      allowHigherOrderFunctions: true
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/no-use-before-define": off

  # need for fast move to ts
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/ban-types": off
  "@typescript-eslint/ban-ts-ignore": off
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/explicit-module-boundary-types": off
